name: Send Weekly Summary

on:
  schedule:
    - cron: '0 7 * * 1'  # Se ejecuta todos los lunes a las 7:00 AM UTC
  workflow_dispatch:     # Permite ejecutar el flujo de trabajo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        PYTHONPATH: ${{ github.workspace }}  # Agregar la ruta raíz del repositorio al PYTHONPATH
      run: |
        python scripts/send_weekly_summary.py
